#! /bin/sh
setxkbmap es
pgrep -x sxhkd > /dev/null || sxhkd &
bash ~/.config/polybar/launch.sh
feh --bg-fill ~/.config/wall.png
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color '#C200E9'
bspc config focused_border_color    '#C200E9'
bspc config unfocus_border_color  '#C200E9'
bspc config active_border_color	    '#C200E9'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
picom -b
