#! /bin/sh
setxkbmap es
pgrep -x sxhkd > /dev/null || sxhkd &
bash ~/.config/polybar/launch.sh
feh --bg-fill ~/.config/wall.png
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color '#30E8E8'
bspc config focused_border_color    '#30E8E8'
bspc config unfocus_border_color  '#C200E9'
bspc config active_border_color	    '#C200E9'

picom -b
