#!/usr/bin/env sh

## Components
pacman -Syy && pacman -S terminus-font picom feh --noconfirm

## install fonts
sudo mv polybar/fonts/ /usr/share/fonts/

## install polybar
rm -r $HOME/.config/polybar
sleep 2s
mv polybar $HOME/.config/

## wallpaper
mv wallpaper/wall.png $HOME/.config

## config BSPWM
rm $HOME/.config/bspwm/bspwmrc
mv bspwmrc $HOME/.config/bspwm/

